### ISSUE TITLE
EE-MPI Patient Unknown

### ISSUE THREAD

**Issue by KristiinaKuldkepp** [HL7EE/ig-ee-mpi#2]
Miks on ValueSet: Unknown Patient Identity Systems toodud eraldi välja PERH? See kuuluks justkui Example alla, mitte ainsa TTO-na valuea-setti? 
![image](https://github.com/HL7EE/ig-ee-mpi/assets/133873675/2e090a62-b786-4b73-a53e-a097b8b975d6)

**Comment by igorboss** [comment]
Antud tulemus vastab value seti valemile (expansionile). Palun koosta nimekirja raviasutustest (äriregistrikood ja nimetus) ja impordime kõiki kohe sisse.

**Comment by ragneoitspuu** [comment]
Jääb hetkel nii nagu on.
