### ISSUE TITLE
UpTIS tiimi kommentarid

### ISSUE THREAD

**Issue by KristiinaKuldkepp** [HL7EE/ig-ee-mpi#3]
Identifikaatorid lehel:
1. "EEBase" link ei tööta
2. "MR numbri genereerimiseks" link viib valesse kohta

Juhend arendajale lehel:
3. Postman "kollektsiooni" link viib lihtsalt samale lehele
4. "mitte inimpatsientide" link ei vii kuhugi (kui ei peagi viima, siis võiks lingi eemaldada)

Patsientide sidumine ja lahti sidumine lehel:
5. Ei saa sellest lausest aru "Unmerge operatsiooni ei eksisteeri, ehk tegemist mitte idempotentse tegevusega" ja ei osanud ka korrigeerida. Mida "idempotentse tegevuse" all silmas peeti?

6. Lehekülg https://fhir.ee/ig/mpi/build/artifacts.html on hetkel poolenisti inglise/poolenisti eesti keeles.
Kogu juhend võiks olla samas keeles. Kas selle lehe saaks ära tõlkida ja eesti keeles presenteerida?

7. Keeleline osa kehtib ka üldise veebikeskkonna suhtes. 
Nt ülamenüü esimene valik on „Home“, järgmine „Juhendid“.
Menüüpunkti „Muu“ alt leiab „Contact Us“, „Downloads“ ja „FHIR Spec“.
Minu jaoks läks vähe keeruliseks, et õiged kohad üles leida nende muutmiseks.

@igorboss - tahaks täna balloti välja kuulutada - kas jõuab muudatused tehtud?

**Comment by igorboss** [comment]
1. Suunasin EEBase root lehele.
2. +
3. Loodetavasti tuleb nädala lõpus
4. +
5. idempotentne = tegevus mis annab sama tulemust, ehk tegevus mida saab korrata. Sõnastasin ringi "MPI ei paku antud operatsiooni patsientide liitmiseks, kuna ta ei ole tagasipööratav."
6. sellega tuleb tegeleda (võtab 1-2 päeva)
7. https://github.com/HL7EE/ig-ee-mpi/blob/master/ig/sushi-config.yaml -> "menu"
